import { ResultType } from "../components/ResultTable/ResultTable";
import TableHelper from "../components/TableHelper/TableHelper";

export const columns = (data: ResultType[]) => [
  {
    title: "ID продукта",
    dataIndex: "prosept_product_id",
    key: "prosept_product_id",
    ...TableHelper.getNumberColumnSearchProps("prosept_product_id"),
    sorter: (a: ResultType, b: ResultType) => a.prosept_product_id - b.prosept_product_id,
  },
  {
    title: "Артикул",
    dataIndex: "article",
    key: "article",
    ...TableHelper.getStringListColumnSearchProps("article", data),
    sorter: (a: ResultType, b: ResultType) => a.article.length - b.article.length,
  },
  {
    title: "Код товара",
    dataIndex: "ean_13",
    key: "ean_13",
    ...TableHelper.getStringListColumnSearchProps("ean_13", data),
    sorter: (a: ResultType, b: ResultType) => a.ean_13.length - b.ean_13.length,
  },
  {
    title: "Стоимость",
    dataIndex: "cost",
    key: "cost",
    ...TableHelper.getNumberColumnSearchProps("cost"),
    sorter: (a: ResultType, b: ResultType) => a.cost - b.cost,
  },
  {
    title: "МРРЦ",
    dataIndex: "min_rec_price",
    key: "min_rec_price",
    ...TableHelper.getNumberColumnSearchProps("min_rec_price"),
    sorter: (a: ResultType, b: ResultType) => (a.min_rec_price || 0) - (b.min_rec_price || 0),

  },
  {
    title: "РРЦ",
    dataIndex: "rec_price",
    key: "rec_price",
    ...TableHelper.getNumberColumnSearchProps("rec_price"),
    sorter: (a: ResultType, b: ResultType) => a.rec_price - b.rec_price,
  },
  {
    title: "Категория товара",
    dataIndex: "category_id",
    key: "category_id",
    ...TableHelper.getNumberColumnSearchProps("category_id"),
    sorter: (a: ResultType, b: ResultType) => a.category_id - b.category_id,
  },
  {
    title: "1С",
    dataIndex: "name_1c",
    key: "name_1c",
    width: 300,
    ...TableHelper.getStringListColumnSearchProps("name_1c", data),
    sorter: (a: ResultType, b: ResultType) => a.name_1c.length - b.name_1c.length,
  },
  {
    title: "Статус",
    dataIndex: "status",
    key: "status",
    ...TableHelper.getStringListColumnSearchProps("status", data),
    sorter: (a: ResultType, b: ResultType) => a.status.length - b.status.length,
  },
  {
    title: "Дата разметки",
    dataIndex: "status_datetime",
    key: "status_datetime",
    ...TableHelper.getStringListColumnSearchProps("status_datetime", data),
    sorter: (a: ResultType, b: ResultType) => a.status_datetime.length - b.status_datetime.length,
  },
  {
    title: "Продукт дилера",
    dataIndex: "product_name",
    key: "product_name",
    width: 300,
    ...TableHelper.getStringListColumnSearchProps("product_name", data),
    sorter: (a: ResultType, b: ResultType) => a.product_name.length - b.product_name.length,
  },
  {
    title: "Дилер",
    dataIndex: "dealer_name",
    key: "dealer_name",
    ...TableHelper.getStringListColumnSearchProps("dealer_name", data),
    sorter: (a: ResultType, b: ResultType) => a.dealer_name.length - b.dealer_name.length,
  },
  {
    title: "Стоимость дилера",
    dataIndex: "price",
    key: "price",
    ...TableHelper.getNumberColumnSearchProps("price"),
    sorter: (a: ResultType, b: ResultType) => a.cost - b.cost,
  },
  {
    title: "Дата парсинга",
    dataIndex: "date",
    key: "date",
    ...TableHelper.getStringListColumnSearchProps("date", data),
    sorter: (a: ResultType, b: ResultType) => a.date.length - b.date.length,
  },
  {
    title: "OZON",
    dataIndex: "ozon_name",
    key: "ozon_name",
    width: 300,
    ...TableHelper.getStringListColumnSearchProps("ozon_name", data),
    sorter: (a: ResultType, b: ResultType) => a.ozon_name.length - b.ozon_name.length,
  },
  {
    title: "Wildberries",
    dataIndex: "wb_name",
    key: "wb_name",
    width: 300,
    ...TableHelper.getStringListColumnSearchProps("wb_name", data),
    sorter: (a: ResultType, b: ResultType) => a.wb_name.length - b.wb_name.length,
  },
  {
    title: "OZON артикул",
    dataIndex: "ozon_article",
    key: "ozon_article",
    ...TableHelper.getStringListColumnSearchProps("ozon_article", data),
    sorter: (a: ResultType, b: ResultType) => a.ozon_article.length - b.ozon_article.length,
  },
  {
    title: "Wildberries артикул",
    dataIndex: "wb_article",
    key: "wb_article",
    ...TableHelper.getStringListColumnSearchProps("wb_article", data),
    sorter: (a: ResultType, b: ResultType) => a.wb_article.length - b.wb_article.length,
  },
  {
    title: "ЯМ артикул",
    dataIndex: "ym_article",
    key: "ym_article",
    ...TableHelper.getStringListColumnSearchProps("ym_article", data),
    sorter: (a: ResultType, b: ResultType) => a.ym_article.length - b.ym_article.length,
  },
].map(x => ({ ...x, width: (x as any).width || 120 }));
